---
title: "Testing surface functions"
output: html_notebook
---

Testing improvements to surface generation functions.  




```{r setup, include = F}
knitr::opts_chunk$set(warning=FALSE, message=FALSE)
```

Load packages and functions  

```{r}
library(tidyverse)
library(sf)
library(raster)
library(tictoc)
library(here)

source("../../code/fri_surface.R")
source("../../code/season_surface.R")
source("../../code/sev_surface.R")
source("../../code/patch_surface.R")
```

Load yosemite data  

```{r}
## read in shapefiles
yose <- read_sf("../../data/spatial/yosemite.shp")
hucs <- read_sf("../../data/spatial/yose_sheds.shp")
yose_fires <- read_sf("../../data/spatial/yose_mtbs.shp") 

## let's test with one huc10 (Headwaters Merced River)
hmr = filter(hucs, Name == "Headwaters Merced River")

tic() 
fri_surface(landscape = hmr, #shapefile of landsape of interest
            fires = yose_fires, #shapefile containing fire IDs associated with severity rasters
            fire_years = "Year", # label of the fire year column
            start_year = 1984, # Year prior to start of dataset (for landsat: 1983)
            end_year = 2018, # Year after end of dataset (for MTBS: 2018)
            decay_rate = 0.5, # Importance decay rate of the "invisible mosaic", between [0,1)
            out_raster = here("data/scratch/fri_hmr.tif")) #path for writing output rasters
toc()

rold = rast(here("data", "scratch", "fri_1804000801_old.tif"))
r = rast(here("data", "scratch", "fri_1804000801.tif"))
r = rast(here('data', 'scratch', 'fri_hmr.tif'))
```

original fri surface function takes 14.75 seconds for the hmr watershed  
with terra run time is only 5.29 seconds. minor differences at the pixel level, likely do to how rasterizing is done?